version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get install -y unzip
      - curl -O https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - rm -rf terraform
      - unzip -o terraform_1.5.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - cd terraform/environment/dev
      - terraform init
  build:
    commands:
      - terraform plan -var-file="terraform.tfvars"
      - terraform apply -auto-approve -var-file="terraform.tfvars"
